### ISSUE TITLE
List-directory functions not accessible on macOS Sierra

### ISSUE THREAD

**Issue by jeffreypmoran** [automotiveMastermind/prompt#13]
The list-directory shortcuts ("ll", "la", etc.) can not be accessed on macOS Sierra.

System version - macOS 10.12.6
Kernel version - Darwin 16.7.0
Bash version - GNU bash, version 4.4.19(1)-release (x86_64-apple-darwin16.7.0)
Prompt version - 4.0.5 (79b5025bc1f82d2cb91b0d62d1fff5530f13631c)

**Comment by jeffreypmoran** [comment]
A possible fix for this issue might be to move the exclamation point outside of the brackets in the `if` statements in list-directory.sh.

For example,
`if [ ! type "la" 1>/dev/null 2>&1 ]; then`
becomes
`if ! [ type "la" 1>/dev/null 2>&1 ]; then`

**Comment by dmccaffery** [comment]
pull requests are welcome :)
