### ISSUE TITLE
docs: project management replacement

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/prompt#22]
Waffle IO is now defunct. I would like to evaluate alternatives with good support for notifications to both Slack and Microsoft Teams (the two primary communication tools used by our core contributors).

Any ideas on what we want/need here?

**Comment by sjk07** [comment]
Any reason why we shouldn't just use Github project boards? Anyone have experience with using them? 
https://github.com/automotiveMastermind/prompt/projects/1

**Comment by dmccaffery** [comment]
They didn't have automation in the past; but now that I am looking at it -- looks like they basically copied waffle.io automation :)

**Comment by dmccaffery** [comment]
Do you want 1 board for all FOSS or one per project?

**Comment by sjk07** [comment]
Hard to say right now. I can see both having value. If they are automated like waffle then I see no issue trying both and seeing how things pan out.

**Comment by dmccaffery** [comment]
I think my preference is to have it all under the aM project -- keep all the issues across all of the FOSS in one place -- its obvious which repo is associated on the org project board. You good with this? If so, we can close this issue out.

**Comment by sjk07** [comment]
yup works for me. We can always make it more granular if needed.

Closing and making aM the project board moving forward.
