### ISSUE TITLE
dotnet-install error: "unknown argument `__channel`"

### ISSUE THREAD

**Issue by jeffreypmoran** [automotiveMastermind/prompt#45]
When running the "dotnet-install" command, I get the error "dotnet_install: Error: Unknown argument `__channel`".  The issue can be worked around by manually modifying the dotnet-install.sh file and replacing "__channel" (two underscores) with "--channel" (two hyphens).

The issue appears to affect the "version" argument as well.

**Comment by dmccaffery** [comment]
Interesting. Thanks for the bug report. Likely a find-replace issue at some point during the zsh makeover.
