### ISSUE TITLE
Error when attempting to install a specific version of prompt

### ISSUE THREAD

**Issue by jaaydenh** [automotiveMastermind/prompt#48]
When attempting to run this command:
```curl -fsSL https://git.io/am-prompt | sh -s -- --version v7.0.0 bash```

it returns this error:
```sh: line 90: pushd: prompt-master: No such file or directory```

This also happens when replacing v7.0.0 with other versions such as v6.3.1

**Comment by dmccaffery** [comment]
Thanks for the bug report. We'll take a look.
