### ISSUE TITLE
gcloud-install: sources bash completion in sh/zsh

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/prompt#50]
The `gcloud-install` assumes bash and sources bash completion scripts in all shells

**Comment by dmccaffery** [comment]
This is still an issue; keep it open mr stale not!

**Comment by sjk07** [comment]
Is there a simple way to deal with this? or is this on glcloud side?

**Comment by dmccaffery** [comment]
its an easy fix; just hasn't been a high priority as everyone I know is using either bash or zsh (rather than a POSIX shell)

**Comment by sjk07** [comment]
script is now called : `install-gcloud` in v8

Im a little lost on the direction to fix this then. What would be the potential fix here?

**Comment by dmccaffery** [comment]
All scripts in src/sh/scripts should be posix compliant as we don't know what shell will be used on the distro for "sh" -- on Ubuntu, it is dash, but on macOS and many other distributions it is bash.

The install-gcloud script tests for the existence of the bash completion script and sources it, which will fail on posix shells.

To fix, we need to remove the completion check from install-gcloud entirely. This is a left over from when we only supported bash.

We're doing the completion magic today in the respective shell gcloud-path scripts anyway (to detect gcloud installs that weren't necessarily done by the prompt install-gcloud script):

https://github.com/automotiveMastermind/prompt/blob/ff32581d5ef327ce8787cdced147e694acccc1a8/src/zsh/scripts/eval/set-gcloud-path#L26

and

https://github.com/automotiveMastermind/prompt/blob/ff32581d5ef327ce8787cdced147e694acccc1a8/src/bash/scripts/eval/set-gcloud-path#L26

**Comment by dmccaffery** [comment]
note: this has a side-effect of completion not being available until after the terminal is relaunched; but gcloud's own installer doesn't include completion by default (its always a manual-op), so I don't see an obvious downside to this. We could add a message in gcloud-install that tells the caller to restart their terminal to get completion. 

Alternatively, we can duplicate the gcloud-install script in zsh/bash script-dirs with the appropriate sourcing.

Or, we could do some shell detection in the install-gcloud script and source the right one; but that's more complicated than its worth, IMHO.

Lastly, we could run the $AM_PROMPT_SHELL/eval/set-gcloud-path script from the gcloud-install script (if it exists), which simplifies detection -- I think $AM_PROMPT_SHELL is always available regardless of what shell is used to invoke.
