### ISSUE TITLE
I've been getting the same error locally on macOS:

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/prompt#52]
I've been getting the same error locally on macOS:

<img width="865" alt="Screen Shot 2020-05-21 at 11 21 21 AM" src="https://user-images.githubusercontent.com/1302453/82574505-3f046700-9b55-11ea-9963-5638c77bec2d.png">

_Originally posted by @patrickserrano in https://github.com/automotiveMastermind/prompt/pull/51#issuecomment-632146448_

**Comment by patrickserrano** [comment]
Also seeing this when using prompt with Ubuntu and WSL v1:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/1302453/82575691-cb635980-9b56-11ea-9fbc-8707759a11a1.png">

**Comment by dmccaffery** [comment]
haha -- it hates you -- I cannot repro on either macOS or in WSL 2 (have not tried WSL 1)

**Comment by sjk07** [comment]
yeah this is interesting, I also can't repro on macOS

**Comment by dmccaffery** [comment]
@patrickserrano : still seeing this issue?

**Comment by patrickserrano** [comment]
@dmccaffery I'm not. I'm going to chalk it up to something with my system and close it.

**Comment by patrickserrano** [comment]
@dmccaffery or maybe not? I don't think I have the permission to close this, even though it's my issue?

**Comment by sjk07** [comment]
@patrickserrano closed by your request. 😄
