### ISSUE TITLE
docs(readme): update readme and fix typos

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/prompt#7]
There are a few typos in the readme. 

We should also update the readme to follow our default guidelines at aM.

- [x] screenshot of how the prompt looks (suggestion from #9)
- [x] table for project info
- [x] table for major credits
- [x] install instructions
- [ ] list of features
    - [ ] git prompt
    - [ ] user variables
    - [ ] bookmarking
    - [ ] user bashrc
- [ ] list of available commands
    - [ ] all platforms
    - [ ] Darwin (macOS)
- [ ] reference CREDITS

**Comment by sjk07** [comment]
Looks like this never actually got done. reopenning

**Comment by dmccaffery** [comment]
@tiffanywang3 ever going to do this?

**Comment by dmccaffery** [comment]
@tiffanywang3 bump (again)

**Comment by tiffanywang3** [comment]
:feelsbadman: I'm going to remove myself from this task for now in case anyone else is able to get to this before me. Not sure why I closed it
